[th/fix-sriov-mac-addrs] fix regression for parsing SR-IOV VFs from netlink
nispor/nispor pull request #199
Opened 2022-06-15 23:22 UTC by thom311

Commit 25f186819f0e changes `mac::parse_as_mac()` to be strict. However, SR-IOV VFs (`IFLA_VF_MAC`, `IFLA_VF_BROADCAST`) are not only 6 bytes long. Hence, the entire VF failed to parse. The effect is, that it appears as if there is no VF.

Fix that by relaxing the check. Also a few followup patches for consideration.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2090678

2022-06-16 06:32 UTC, thom311 commented
it's easy to reproduce.

- Have a machine with SR-IOV interface.
- Create a VF (`echo 1 > /sys/class/net/p4p1/device/sriov_numvfs`)
- run `./target/debug/npc iface`.
- Note:
```
    sriov:
      vfs: []
```
That is wrong. There should be a VF.

2022-06-23 13:42 UTC, cathay4t commented
@thom311 I think this bug is about nispor not supporting MAC address of SR-IOV inifiniband which seems the first commit is enough to fix the problem. Why we need other 3 commits?

2022-06-23 15:13 UTC, thom311 commented
> @thom311 I think this bug is about nispor not supporting MAC address of SR-IOV inifiniband which seems the first commit is enough to fix the problem. Why we need other 3 commits?

To "improve" the code. Feel free to drop them, if you don't like them.

2022-06-24 08:16 UTC, cathay4t commented
Please try to use another PR to improve the code. Thanks!

2022-06-24 08:49 UTC, thom311 commented
the followup patches are of course strongly related. The commit message tries to explain what they do, and why they are there.
I reworded the commit message to make it clearer. Also, rebased the branch.

2022-06-24 08:52 UTC, thom311 commented
> I think this bug is about nispor not supporting MAC address of SR-IOV inifiniband

That is not correct. nispor fails to parse the MAC address also for Ethernet, thus it fails to parse all SR-IOV data. I described how to reproduce it in https://github.com/nispor/nispor/pull/199#issuecomment-1157286327 .

2022-06-24 09:51 UTC, cathay4t requested changes

2022-06-24 09:51 UTC, cathay4t commented on src/lib/mac.rs
> +    if data.len() < mac_len {
If we already know the `mac_len`, then we should passing the correct `mac_len` to this function instead of change this line.

2022-06-24 10:14 UTC, thom311 commented on src/lib/mac.rs
> +    if data.len() < mac_len {
The correct mac-len is passed. The buffer contains 32 bytes, but we only want to take the first 6 (`ETH_ALEN`) bytes.

Maybe instead the caller should be required to only pass a slice of up to `mac_len` bytes for `data`. But we also don't require the caller to do that for `crate::netlink::parse_as_u32()`.

2022-06-24 12:11 UTC, cathay4t commented on src/lib/mac.rs
> +    if data.len() < mac_len {
In that case, `<` is the correct fix.

2022-06-28 14:41 UTC, cathay4t approved these changes
LGTM. Thanks!

2022-06-28 14:45 UTC, merged