veth: fix report of veth peer on a different netns
nispor/nispor pull request #201
Opened 2022-06-22 08:41 UTC by ffmancera

When the veth peer is on a different netns, the ifindex counting start
from "1" again. That means, if the veth has ifindex 30 one could expect
the peer will have ifindex 31 but if it is on a different netns, the
ifindex could be completetly different, e.g "2".

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2022-06-22 09:10 UTC, cathay4t commented
We should skip the interface name lookup when the `IFLA_LINK_NETNSID` is defined.

2022-06-22 17:15 UTC, ffmancera commented
> We should skip the interface name lookup when the `IFLA_LINK_NETNSID` is defined.

It won't work because the LINK_NETNSID is the ID of the NETNS where the veth interface is.. not the peer. In nispor we do not have information about other netns interfaces yet. We need to support multi-netns state querying.. 

What do you think about this solution? It checks that the veth peer and the peer iface matches in name.

2022-06-23 00:09 UTC, cathay4t commented
The `IFLA_LINK_NETNSID` is the NSID of veth **peer**. https://www.spinics.net/lists/netdev/msg317678.html You may try `strace -s 1024 ip -d link` to get it.

2022-06-23 09:02 UTC, ffmancera commented
> The `IFLA_LINK_NETNSID` is the NSID of veth **peer**. https://www.spinics.net/lists/netdev/msg317678.html You may try `strace -s 1024 ip -d link` to get it.

You are right. My bad, I misread it. I added a new patch supporting netnsid. I tested it and it works as expected :)

2022-06-24 11:04 UTC, ffmancera commented
@cathay4t Take a look when you have time, thank you!

2022-06-28 14:08 UTC, cathay4t requested changes

2022-06-28 14:08 UTC, cathay4t commented on src/lib/ifaces/iface.rs
> +    pub netnsid: Option<i32>,
This is `netnsid` might confused with namespace ID of this interface. Since the kernel is using `IFLA_LINK_NETNSID`, we can use `link_netnsid` as property name indicating the underline link is in another network namespace.

2022-06-28 14:19 UTC, ffmancera commented on src/lib/ifaces/iface.rs
> +    pub netnsid: Option<i32>,
Done, thank you!

2022-06-28 14:20 UTC, cathay4t approved these changes

2022-06-28 14:24 UTC, merged