Use `NlasIterator` and `NlaBuffer` instead of parsing by ourselves
nispor/nispor pull request #21
Opened 2020-08-28 10:38 UTC by qinqon

Closes: #17

Signed-off-by: Quique Llorente <ellorent@redhat.com>

2020-08-28 11:15 UTC, qinqon commented
Have set arp_ip_target on the bond and looks like npc is dumping it correctly so I suppose is working fine this part.

2020-09-02 11:44 UTC, qinqon commented
/cc @cathay4t PR ready

2020-09-02 13:53 UTC, cathay4t requested changes
Thanks for the PR. Please amend base on feedback.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bond.rs
> +        }
Please use `eprintln!()` for errors instead of silently ignore them.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bond.rs
> +                _ => (),
`eprintln!("Unhandled IFLA_BOND_AD_INFO: {} {:?}", nla.kind(), nla.value())`.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bond.rs
> +        if let Ok(nla) = nla {
Please use `eprintln!()` for `Err(e)`.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bond.rs
> +            }
Please use eprintln!() for errors instead of silently ignore them.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bond.rs
> +        if let Ok(nla) = nla {
Please use eprintln!() for errors instead of silently ignore them.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bridge_port.rs
> +            }
Please use eprintln!() for errors instead of silently ignore them.

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/bridge_vlan.rs
> +                        "unknown nla_kind, {}, nla_value: {:?}",
All other code are using `Unhandled XXX: {} {:?}".

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/vxlan.rs
> +                _ => eprintln!("Unknwon nla_type {}, {:?}", nla.kind(), nla.value()),
`eprintln!("Unhandled VxLAN IFLA_INFO_DATA: {}, {:?}", nla.kind(), nla.value())`

2020-09-02 13:53 UTC, cathay4t commented on src/lib/netlink/vxlan.rs
> +                _ => eprintln!("Unknwon nla_type {}, {:?}", nla.kind(), nla.value()),
We need more context when the error happens as many InfoData are sharing the same value of `nla.kind()` in kernel.

2020-09-10 06:52 UTC, qinqon commented
/cc @cathay4t can you take a look ?

2020-09-21 08:19 UTC, qinqon commented
rebased

2020-09-21 12:52 UTC, cathay4t approved these changes

2020-09-21 12:53 UTC, merged