Manpage for npc
nispor/nispor pull request #84
Opened 2020-11-07 19:46 UTC by shreyagupta30

this partly tackles #18 . I have added manpage for npc.

2020-11-09 06:46 UTC, cathay4t commented
@shreyagupta30 
Thanks for the contribution.

Could you:
 * Merge the commits into one?
 * Could you expand the manpage a little bit by mentioning the filtering stufff?
  * npc eth1
  * npc route --dev eth1

2020-11-09 12:09 UTC, shreyagupta30 commented
Hi @cathay4t!
Thanks for the review. I will make the requested changes. Could you please elaborate on what filtering, npc eth1 and npc route --dev eth1 mean? I am not sure if I understand it fully.

2020-11-10 08:57 UTC, ffmancera commented
> Hi @cathay4t!
> Thanks for the review. I will make the requested changes. Could you please elaborate on what filtering, npc eth1 and npc route --dev eth1 mean? I am not sure if I understand it fully.

Well, in order to use `npc`, a user could do `npc interface_name` and this will show only the interface state. In addition, the user can run `npc route` to show all the network routes or  `npc route --dev interface_name` to show up all the routes related to that interface.

In addition, the user can do `npc rules` in order to list all the network route rules.

2020-11-10 09:03 UTC, ffmancera requested changes

2020-11-10 09:03 UTC, ffmancera commented on npc
> +npc route \- Print route entries
This should be in the synopsis section.

2020-11-10 09:03 UTC, ffmancera commented on npc
> +npc is a command line tool that has all the network status.
In addition, the description section should contain detailed description of all commands.

2020-11-10 15:05 UTC, cathay4t commented
Another thing I forgot to mention: please also update Makefile so that manpage could installed to correct folder by command `make install`.

2020-11-16 20:10 UTC, shreyagupta30 commented
Hi @ffmancera and @cathay4t! I have made the requested changes and it's ready for review. Do let me know if any further changes are required.

2020-11-18 15:09 UTC, cathay4t requested changes
Makefile need more work.

The manpage change request is optional. I can amend them later in better sharp.

2020-11-18 15:09 UTC, cathay4t commented on Makefile
> +install-man: nispor.3
There is no `nispor.3` file in this PR.

2020-11-18 15:09 UTC, cathay4t commented on Makefile
> +    ln -s nispor.3 $(mandir)/man3/npc.3
Why `ln` is required?

2020-11-18 15:09 UTC, cathay4t commented on npc
> +.\" Manpage for npc.
This file should be placed as `doc/npc.1` instead of top code folder.

The command line tool manpage should be in section 1.

2020-11-18 15:09 UTC, cathay4t commented on npc
> +.TH npc "04 Nov 2020" "0.6.1"
The `Makefile` has `CLIB_VERSION` which you can be used for generate this manage with correct version number.

You may take `CLIB_HEADER_IN` as example in `Makefile`

2020-11-18 15:09 UTC, cathay4t commented on npc
> +npc route --dev interface_name \- Print routes for the particular interface name
Normally, manapge use `npc route --dev [INTERFACE_NAME]` format.

Meanwhile, use something like:

```
.SH "GLOBAL OPTIONS"
.TP 15
\fB-j\fR, \fB--json\fR
Show in json format.

.SH COMMANDS
.SS npc [INTERFACE_NAME]

.SS npc route
.TP 15
\fB-d\fR, \fB--dev\fR, 

limit output route for specified interface.
```

2020-11-18 15:09 UTC, cathay4t commented on npc
> +.SH REPORTING BUGS
Please also include your name in `.SH AUTHOR`.

2020-11-18 15:10 UTC, cathay4t commented
Meanwhile, please rebase and use single patch for this PR.

2022-03-15 00:13 UTC, cathay4t commented
Closing as 1+ year has passed without update.

2022-03-15 00:13 UTC, closed without merging